### ISSUE TITLE
Test Checkpoint.

### ISSUE THREAD

**Issue by Kiet0712** [PuFanqi23/MonoDGP#2]
Hi. Thank you for your great work, but can you release the config file for training trainval set and how can you choose the best checkpoint to be submitted to KITTI server?
Thank you!

**Comment by PuFanqi23** [comment]
Hi. Thank you for your interest in MonoDGP. 
We utilize the same config for both the training and trainval sets. Since there are no labels for the test set, we select the checkpoint that performs best on the trainval set, which is among the last few checkpoints. Remember to change train_split and test_split in  [configs/monodgp.yaml](configs/monodgp.yaml) if you want to train on the whole trainval set.
Feel free to reach out if you have any questions!
