### ISSUE TITLE
Some implementation issues

### ISSUE THREAD

**Issue by Ecalpal** [PuFanqi23/MonoDGP#3]
Thank you for your excellent work! 
﻿
I believe that simply providing the test set weights and results already strengthens the credibility of your work significantly, setting it apart from many previous studies.
﻿
I’ve noticed that several individuals ([#69](https://github.com/ZrrSkywalker/MonoDETR/issues/69), [#48](https://github.com/ZrrSkywalker/MonoDETR/issues/48), [#46](https://github.com/ZrrSkywalker/MonoDETR/issues/46), [#24](https://github.com/ZrrSkywalker/MonoDETR/issues/24)) involved in the MonoDETR project have encountered difficulties when trying to reproduce the results reported in their paper.

Have you experienced any similar challenges during the implementation process? Additionally, since your work builds upon MonoDETR, are there any unstable situations or issues that you have encountered in a similar manner?

**Comment by PuFanqi23** [comment]
Hi, Thanks for your interest in MonoDGP!

I would like to first appreciate the great work MonoDETR for providing a powerful monocular detection framework. The current version of MonoDETR code mainly supports A100  and may perform a little lower on 3090. I also got about 18% Moderate $AP_{3d|R40}$ for the Car category using the default config in MonoDETR repo on 3090. 

In order to reproduce the paper performance, we have taken the following steps:

1、Follow the MonoDETR author's [advice](https://github.com/ZrrSkywalker/MonoDETR/issues/51) and turn the model to the original version for 3090. At this time, we can achieve about 19.8% ~ 20.2% $AP_{3d|R40}$ on the val set.

2、We found that during the training process, the model's performance remained constant from 85 to 125 epoch, so we add 85 to the decay list and increase the decay rate.

3、We also adopt Mixup for data augmentation in [lib/datasets/kitti/kitti_dataset.py](https://github.com/PuFanqi23/MonoDGP/blob/d4be5f6f4b2d152389eae649af320f2f5798a48c/lib/datasets/kitti/kitti_dataset.py).

After three steps, we can reproduce a better $AP_{3d|R40}$ result between 20.5% and 21.1%  (We select average performance 20.79% in our paper). Based on these changes, we further construct MonoDGP model. I suppose that MonoDETR submits test results to the KITTI website several times and reports the best one in their paper.

The unstable issue also disturbs MonoDGP, our newest results for MonoDGP can even reach [23.02%](https://github.com/user-attachments/files/17986798/23_02.log) on the val set. Therefore, we select median AP 22.34% from five experiments conducted on the val set and report best results on the test set. For MonoDGP, there still lacks a stable training method that converges the model to the best results.

I hope this helps, and let me know if anything else comes up.

**Comment by Ecalpal** [comment]
Thank you for your detailed reply!

**Comment by Aangss** [comment]
> Hi, Thanks for your interest in MonoDGP!
> 
> I would like to first appreciate the great work MonoDETR for providing a powerful monocular detection framework. The current version of MonoDETR code mainly supports A100 and may perform a little lower on 3090. I also got about 18% Moderate A P 3 d | R 40 for the Car category using the default config in MonoDETR repo on 3090.
> 
> In order to reproduce the paper performance, we have taken the following steps:
> 
> 1、Follow the MonoDETR author's [advice](https://github.com/ZrrSkywalker/MonoDETR/issues/51) and turn the model to the original version for 3090. At this time, we can achieve about 19.8% ~ 20.2% A P 3 d | R 40 on the val set.
> 
> 2、We found that during the training process, the model's performance remained constant from 85 to 125 epoch, so we add 85 to the decay list and increase the decay rate.
> 
> 3、We also adopt Mixup for data augmentation in [lib/datasets/kitti/kitti_dataset.py](https://github.com/PuFanqi23/MonoDGP/blob/d4be5f6f4b2d152389eae649af320f2f5798a48c/lib/datasets/kitti/kitti_dataset.py).
> 
> After three steps, we can reproduce a better A P 3 d | R 40 result between 20.5% and 21.1% (We select average performance 20.79% in our paper). Based on these changes, we further construct MonoDGP model. I suppose that MonoDETR submits test results to the KITTI website several times and reports the best one in their paper.
> 
> The unstable issue also disturbs MonoDGP, our newest results for MonoDGP can even reach [23.02%](https://github.com/user-attachments/files/17986798/23_02.log) on the val set. Therefore, we select median AP 22.34% from five experiments conducted on the val set and report best results on the test set. For MonoDGP, there still lacks a stable training method that converges the model to the best results.
> 
> I hope this helps, and let me know if anything else comes up.

I'm curious, if I reproduce this work on A800, should I add the deleted lines of code back to DepthAwareDecoderLayer? Because it's currently targeting 3090, I don't know if my idea is correct.
